#!/usr/bin/bash
[ $# -eq 1 ] || { echo 'Usage: measure_all <scenario>'; exit 1; }

[ -e 'out/$1' ] || mkdir -p out/$1

while read algo formats
do
  echo $algo
  ./measure.py $1 $algo | tee out/$1/$algo
done < algorithms
./plot.py $1
