#!/usr/bin/bash
[ $# -eq 1 ] || { echo 'Usage: measure_all <scenario>'; exit 1; }

[ -e 'out/$1' ] || mkdir -p out/$1

for algo in BFS paraBFS DFS TLS TLS64 RecMerge RTLS
do
  echo $algo
  ./measure.py $1 $algo | tee out/$1/$algo
done
./plot.py $1
